/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FavoritController;
import Database.FavoritDB;
import Model.Resep;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author armed
 */
public class FavoritFrame extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form FavoritFrame
     */
    public FavoritFrame(String username) {
        this.username = username;
        initComponents();
        loadKonten();
    }

    public FavoritFrame() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        konterFavorit = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblPenulis = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnLihatResep = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilanFavorit = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();

        konterFavorit.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 26, 10, 26));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 115));
        jPanel8.setLayout(new java.awt.BorderLayout());

        lblNama.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblNama.setText("Nama");
        jPanel8.add(lblNama, java.awt.BorderLayout.PAGE_START);

        lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Folder/croissant.jpeg"))); // NOI18N
        jPanel8.add(lblGambar, java.awt.BorderLayout.CENTER);

        konterFavorit.add(jPanel8, java.awt.BorderLayout.WEST);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 26));
        jPanel9.setPreferredSize(new java.awt.Dimension(170, 115));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lblPenulis.setText("Penulis");
        jPanel9.add(lblPenulis, java.awt.BorderLayout.CENTER);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel10.setLayout(new java.awt.BorderLayout());

        btnLihatResep.setText("Lihat Resep");
        btnLihatResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatResepActionPerformed(evt);
            }
        });
        jPanel10.add(btnLihatResep, java.awt.BorderLayout.LINE_END);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Folder/icons8-delete-30.png"))); // NOI18N
        btnHapus.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel10.add(btnHapus, java.awt.BorderLayout.LINE_START);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        lblKategori.setText("Kategori");
        jPanel9.add(lblKategori, java.awt.BorderLayout.PAGE_START);

        konterFavorit.add(jPanel9, java.awt.BorderLayout.EAST);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 68, 50));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Favorite Dessert");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tampilanFavorit.setBackground(new java.awt.Color(50, 68, 50));
        tampilanFavorit.setPreferredSize(new java.awt.Dimension(359, 1000));
        jScrollPane1.setViewportView(tampilanFavorit);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatResepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatResepActionPerformed

    private void tambahKonten(Resep resep) {
        JPanel konterFavorit = new JPanel();
        konterFavorit.setLayout(new java.awt.BorderLayout());
        JPanel jPanel8 = new JPanel();
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 26, 10, 26));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 115));
        jPanel8.setLayout(new java.awt.BorderLayout());

        JLabel lblNama = new JLabel();
        lblNama.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblNama.setText(resep.getNama());
        jPanel8.add(lblNama, java.awt.BorderLayout.PAGE_START);

        JLabel lblGambar = new JLabel();
        tampilGambar(resep.getGambar(), lblGambar);
        jPanel8.add(lblGambar, java.awt.BorderLayout.CENTER);

        konterFavorit.add(jPanel8, java.awt.BorderLayout.WEST);

        JPanel jPanel9 = new JPanel();
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 26));
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 115));
        jPanel9.setLayout(new java.awt.BorderLayout());

        JLabel lblPenulis = new JLabel();
        lblPenulis.setText(resep.getPenulis());
        jPanel9.add(lblPenulis, java.awt.BorderLayout.CENTER);

        JLabel lblKategori = new JLabel();
        lblKategori.setText(resep.getKategori());
        jPanel9.add(lblKategori, java.awt.BorderLayout.PAGE_START);

        JPanel jPanel10 = new JPanel();
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel10.setLayout(new java.awt.BorderLayout());

        JButton btnLihatResep = new JButton();
        btnLihatResep.setText("Lihat Resep");
        btnLihatResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String kategori = lblKategori.getText();  // Gantilah dengan cara Anda mendapatkan kategori dari label

                // Jika kategori adalah "Nasional"
                if ("nasional".equalsIgnoreCase(kategori)) {
                    new DetailResepNasional(resep.getIdResep(), username).setVisible(true);
                } // Jika kategori adalah "Internasional"
                else if ("internasional".equalsIgnoreCase(kategori)) {
                    new DetailResepInternasional(resep.getIdResep(), username).setVisible(true);
                }
            }
        });
        jPanel10.add(btnLihatResep, java.awt.BorderLayout.LINE_END);

        JButton btnHapus = new JButton();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Aset/Folder/icons8-delete-30.png"));
        Image scaledImage = icon.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        btnHapus.setIcon(new ImageIcon(scaledImage));  // Set the scaled icon
        btnHapus.setPreferredSize(new java.awt.Dimension(23, 23));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritController favoritDB = new FavoritDB();
                favoritDB.deleteFavorit(resep.getIdResep(), username);

                // Tampilkan pesan sukses
                JOptionPane.showMessageDialog(null, "Favorit berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                // Refresh tabel favorit
                loadKonten();
            }
        });
        jPanel10.add(btnHapus, java.awt.BorderLayout.LINE_START);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        konterFavorit.add(jPanel9, java.awt.BorderLayout.EAST);

        // Tambahkan kartu ke panel utama
        tampilanFavorit.add(konterFavorit);
    }

    private void tampilGambar(String path, JLabel lblGambar) {
        File file = new File(path);

        // Validasi apakah file ada
        if (!file.exists()) {
            lblGambar.setIcon(null);
            lblGambar.setText("Gambar tidak ditemukan");
            return;
        }

        try {
            // Membaca file gambar dari path
            byte[] img = Files.readAllBytes(file.toPath());
            ImageIcon imageIcon = new ImageIcon(img);

            // Dimensi label
            int labelWidth = 105;
            int labelHeight = 70;

            // Menghitung skala gambar agar sesuai dengan label
            int imageWidth = imageIcon.getIconWidth();
            int imageHeight = imageIcon.getIconHeight();

            double scaleX = (double) labelWidth / (double) imageWidth;
            double scaleY = (double) labelHeight / (double) imageHeight;
            double scale = Math.min(scaleX, scaleY);

            // Melakukan scaling pada gambar
            Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeight), Image.SCALE_SMOOTH);

            // Menampilkan gambar ke label
            lblGambar.setIcon(new ImageIcon(scaledImage));
            lblGambar.setText(""); // Hapus teks jika gambar berhasil ditampilkan
        } catch (IOException ex) {
            ex.printStackTrace();
            lblGambar.setIcon(null);
            lblGambar.setText("Gagal memuat gambar");
        }
    }

    private void loadKonten() {
        tampilanFavorit.removeAll();

        FavoritDB favDB = new FavoritDB();

        // Ganti showDataByKategori dengan getFavorit untuk mendapatkan data favorit berdasarkan username
        List<Resep> resepList = favDB.getFavorit(username);

        for (Resep resep : resepList) {
            tambahKonten(resep);  // Menambahkan setiap resep ke tampilan
        }

        tampilanFavorit.revalidate();
        tampilanFavorit.repaint();
    }

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        DashboardFrame df = new DashboardFrame(username);
        df.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FavoritFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FavoritFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FavoritFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FavoritFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FavoritFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLihatResep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel konterFavorit;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPenulis;
    private javax.swing.JPanel tampilanFavorit;
    // End of variables declaration//GEN-END:variables
}
