/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.KomentarDB;
import Database.NotifDB;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Model.Komentar;
import Model.Notifikasi;
import Model.ValidasiInputException;
import java.util.List;

/**
 *
 * @author armed
 */
public class KomentarFrame extends javax.swing.JFrame {

    private String username;
    private int idResep;

    /**
     * Creates new form KomentarFrame
     */
    public KomentarFrame(int id, String username) {
        this.username = username;
        this.idResep = id;
        initComponents();
        loadKomen();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public KomentarFrame() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontenKomentar = new javax.swing.JPanel();
        txtUsername = new javax.swing.JLabel();
        lblKomentar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        txtKomentar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilanKomentar = new javax.swing.JPanel();

        kontenKomentar.setBackground(new java.awt.Color(255, 255, 255));
        kontenKomentar.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 14, 16, 14));
        kontenKomentar.setLayout(new java.awt.BorderLayout());

        txtUsername.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txtUsername.setText("Farin Armeda");
        txtUsername.setPreferredSize(new java.awt.Dimension(220, 15));
        kontenKomentar.add(txtUsername, java.awt.BorderLayout.PAGE_START);

        lblKomentar.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        lblKomentar.setForeground(new java.awt.Color(102, 102, 102));
        lblKomentar.setText("Resepnya enak banget ka!!!");
        lblKomentar.setPreferredSize(new java.awt.Dimension(220, 50));
        kontenKomentar.add(lblKomentar, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 68, 50));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comments");

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSend)
                    .addComponent(txtKomentar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtKomentar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend)
                .addGap(15, 15, 15))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tampilanKomentar.setBackground(new java.awt.Color(204, 204, 204));
        tampilanKomentar.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        tampilanKomentar.setPreferredSize(new java.awt.Dimension(300, 1000));
        tampilanKomentar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 12));
        jScrollPane1.setViewportView(tampilanKomentar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String penulis = username;
        String isi = txtKomentar.getText();

        try {
            Komentar komen = new Komentar(isi, penulis);
            KomentarDB komenDB = new KomentarDB();
            komenDB.addKomentar(idResep, komen);
        } catch (ValidasiInputException ex) {
            ex.printStackTrace();
        }
        // Memberikan umpan balik kepada pengguna, misalnya dengan menampilkan pesan
        JOptionPane.showMessageDialog(this, "Berhasil menambahkan komentar");
        NotifDB notiDB = new NotifDB();
        Notifikasi notif = new Notifikasi("Berhasil menambahkan komentar", username);
        notiDB.addKomentar(notif);
        loadKomen();
    }//GEN-LAST:event_btnSendActionPerformed

    private void tambahKomen(Komentar komen) {
        JPanel kontenKomentar = new JPanel();
        kontenKomentar.setBackground(new java.awt.Color(255, 255, 255));
        kontenKomentar.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 14, 16, 14));
        kontenKomentar.setLayout(new java.awt.BorderLayout());

        JLabel txtUsername = new JLabel();
        txtUsername.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txtUsername.setText(komen.getPenulis());
        txtUsername.setPreferredSize(new java.awt.Dimension(220, 15));
        kontenKomentar.add(txtUsername, java.awt.BorderLayout.PAGE_START);

        JLabel lblKomentar = new JLabel();
        lblKomentar.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        lblKomentar.setForeground(new java.awt.Color(102, 102, 102));
        lblKomentar.setText(komen.getIsi());
        lblKomentar.setPreferredSize(new java.awt.Dimension(220, 50));
        kontenKomentar.add(lblKomentar, java.awt.BorderLayout.CENTER);

        tampilanKomentar.add(kontenKomentar);
    }

    private void loadKomen() {
        tampilanKomentar.removeAll();

        KomentarDB komenDB = new KomentarDB();

        List<Komentar> komenList = komenDB.showKomentar(idResep);;

        for (Komentar komen : komenList) {
            tambahKomen(komen);  // Menambahkan setiap resep ke tampilan
        }

        tampilanKomentar.revalidate();
        tampilanKomentar.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Komentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Komentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Komentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Komentar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KomentarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kontenKomentar;
    private javax.swing.JLabel lblKomentar;
    private javax.swing.JPanel tampilanKomentar;
    private javax.swing.JTextField txtKomentar;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
